import React from 'react';
import {Container, Jumbotron} from 'react-bootstrap';
import BookManagerList from '../../components/BookManagerList';

/* DUMMY DATA */
const data = [
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: 'In what city did you have your first ever birthday party?',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
  {
    _id: '5e7a1857e7c0e02d7844fe97',
    firstname: 'Book',
    lastname: 'Manager',
    username: 'username',
    password: '',
    email: 'bookmanager@email.com',
    idNumber: '12312312',
    question: '',
    answer: '',
    userType: 'BOOK_MANAGER',
    bookHistory: [],
    salt: '',
    __v: 0,
  },
];

const Page = () => {
  return (
    <>
      <Jumbotron bsPrefix="page-header" fluid>
        <Container className="inner-container">
          <h1 style={{color: '#6C4CC5'}}>Book Manangers</h1>
          <p>
            Manage the book managers of your online library. You can add, edit,
            and delete book managers!
          </p>
        </Container>
      </Jumbotron>

      <div className="content-container">
        <BookManagerList data={data} />
      </div>
    </>
  );
};

export default Page;
