const bookInstanceData = [
  {
    key: 1,
    title: 'Roots',
    authors: ['Rae Kun'],
    status: 'Available',
    available: '2020-04-27 02:13',
  },
  {
    key: 2,
    title: 'Roots',
    authors: ['Rae Kun'],
    status: 'Reserved',
    available: '2020-04-27 02:13',
  },
  {
    key: 3,
    title: 'Roots',
    authors: ['Rae Kun'],
    status: 'Available',
    available: '2020-04-27 02:13',
  },
  {
    key: 4,
    title: 'Roots',
    authors: [
      'Rae Kun',
      'Anne Kun',
      'Raeanne Villanueva',
      'Andrew Ing',
      'Stanley Sie',
    ],
    status: 'Available',
    available: '2020-04-27 02:13',
  },
  {
    key: 5,
    title: 'Roots',
    authors: ['Rae Kun'],
    status: 'Available',
    available: '2020-04-27 02:13',
  },
  {
    key: 6,
    title: 'Roots',
    authors: ['Rae Kun', 'Anne Kun', 'Raeanne', 'Andrew'],
    status: 'Reserved',
    available: '2020-04-27 02:13',
  },
  {
    key: 7,
    title: 'Roots',
    authors: ['Rae Kun'],
    status: 'Available',
    available: '2020-04-27 02:13',
  },
  {
    key: 8,
    title: 'Roots',
    authors: ['Rae Kun'],
    status: 'Reserved',
    available: '2020-04-27 02:13',
  },
  {
    key: 9,
    title: 'Roots',
    authors: ['Rae Kun'],
    status: 'Available',
    available: '2020-04-27 02:13',
  },
  {
    key: 10,
    title: 'Roots',
    authors: ['Rae Kun'],
    status: 'Available',
    available: '2020-04-27 02:13',
  },
  {
    key: 11,
    title: 'Roots',
    authors: ['Rae Kun'],
    status: 'Available',
    available: '2020-04-27 02:13',
  },
];

export default bookInstanceData;
